hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
access_control:
  enabled: true
  policies:
    - tag_query: ''
      plan: ['user:Cipher-08']
      apply: ['user:Sid-Lais']
      apply_autoapprove: ['user:Cipher-08']
      apply_force: ['user:Cipher-08']
